liip_imagine:
    filter_sets: #filto
        thumb:   #nombre del filtro / como lo queramos llamar
            quality: 75  #calidad de la foto
            filters:
                thumbail: #este filtro genera una foto miniatura o pequeña
                    size: [360, 230]
                    mode: outbound
                    



# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
#liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    #driver: "gd"
